config/routes.rb
Rails.application.routes.draw do

  get 'home/about_us'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  root :to => "home#about_us"
  get "home/contacts"

  resources :room_messages
  resources :rooms
  resources :payments

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/room.rb
class Room < ApplicationRecord


  has_many :room_messages, dependent: :destroy, inverse_of: :room

end

app/models/room_message.rb
class RoomMessage < ApplicationRecord
  belongs_to :user
  belongs_to :room, inverse_of: :room_messages

  def as_json(options)
    super(options).merge(user_avatar_url: user.gravatar_url)
  end


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, uniqueness: true, presence: true

  has_many :room_messages, dependent: :destroy

  def gravatar_url
    gravatar_id = Digest::MD5::hexdigest(email).downcase

      "https://gravatar.com/avatar/#{gravatar_id}.png?d=identicon"

    # "https://gravatar.com/avatar/#{gravatar_id}.png"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :username])
    end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  skip_before_action :authenticate_user!, only: [:about_us, :contacts]

  def about_us
  end

  def  contacts
  end


end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
    skip_before_action :authenticate_user!, only: [:new]
  def index
    @payments_count = Payment.count
  end

  def new
  end

  def create
    if user_signed_in?
      @p = Payment.new
      @p.user_id = current_user.id
      @p.tax = params[:tax].round
      @p.revenue = params[:revenue]
      @p.taxes_system = params[:taxes_system]
      @p.save
      render "new"
    end

  end


end

app/controllers/room_messages_controller.rb
class RoomMessagesController < ApplicationController
  before_action :load_entities

  def create
    @room_message = RoomMessage.create user: current_user,
                                       room: @room,
                                       message: params.dig(:room_message, :message)

    RoomChannel.broadcast_to @room, @room_message
  end


  
  protected

  def load_entities
    @room = Room.find params.dig(:room_message, :room_id)
  end



end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  # Loads:
   # @rooms = all rooms
   # @room = current room when applicable
   before_action :load_entities

   def index
     @rooms = Room.all
   end

   def new
     @room = Room.new
   end

   def create
     @room = Room.new permitted_parameters

     if @room.save
       flash[:success] = "Room #{@room.name} was created successfully"
       redirect_to rooms_path
     else
       render :new
     end
   end

   def edit
   end

   def update
     if @room.update_attributes(permitted_parameters)
       flash[:success] = "Room #{@room.name} was updated successfully"
       redirect_to rooms_path
     else
       render :new
     end
   end

   def show
     @room_message = RoomMessage.new room: @room
     @room_messages = @room.room_messages.includes(:user)
   end


   protected

   def load_entities
     @rooms = Room.all
     @room = Room.find(params[:id]) if params[:id]
   end

   def permitted_parameters
     params.require(:room).permit(:name)
   end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/about_us.html.erb
<div class="jumbotron">
  <h2 class="display-8">О нас</h2>
  <h3>
  <p class="lead">

    Веб-сайт осуществляет поддержку владельцов малого бизнеса и ИП в области <%= link_to "расчета", new_payment_path %> и мониторинга налоговых выплат, а также
    предоставляет возможность учавствовать в локальных беседах с пользователями и специалистами в чатах (анонимно) , в которых можно задавать вопросы на волнующие темы,
    заводить полезные знакомства, консультироваться и обмениваться контактами.

  </p>
  </h3>
  <hr class="my-2">
  <h6>
    Также на сайте представлены <%= link_to "контакты", home_contacts_path %> наших сотрудников, которые готовы помочь Вам в области бухгалтерских услуг.
  </h6>

<% unless user_signed_in? %>
  <hr class="my-2">
  <p>
    <%= link_to "Регистрируйтесь",  new_user_registration_path %>, если еще не сделали этого, чтобы воспользоваться сервисом общения с пользователями и мониторинга своих налоговых расчетов.
    </p>

</div>
<% end %>

app/views/home/contacts.html.erb
<hr class="my-2">
<div class="d-flex justify-content-center">


<div class="col-8 " >
<div class="jumbotron">
  <h2 class="display-8">Контакты</h2>

  <p class="lead">



<ul class="list-group">
  <li class="list-group-item d-flex justify-content-between align-items-center">
    Velcom
    <span class="badge badge-primary badge-pill">+375-(29)-288-35-35</span>
  </li>
  <li class="list-group-item d-flex justify-content-between align-items-center">
    MTC
    <span class="badge badge-primary badge-pill">+375-(33)-282-35-75</span>
  </li>
  <li class="list-group-item d-flex justify-content-between align-items-center">
    Life
    <span class="badge badge-primary badge-pill">+375-(33)-112-99-99</span>
  </li>
</ul>

<hr class="my-3">
<h9>
      *** Цены на услуги определяются сложностью выполняемой работы и оговариваются сугубо с представителем ***
</h9>

</div>

</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Taxes</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>


  </head>

  <body>
    <div class="container">
     <div class="row">
       <div class="col-12">
         <%= render partial: 'shared/navigation_bar' %>
         <div class="my-3">
    <%= yield %>
 </div>
  </div>
   </div>
 </div>
  </body>
</html>

app/views/payments/index.html.erb
<hr class="my-2">
<div class="d-flex justify-content-center">

<div class="col-12 " >
    <h2 class="display-8"> Статистика налоговых выплат</h2>
  <div class="jumbotron">



    <% if @payments_count == 0 %>

    <h3>
    <p class="lead">
      Зарегистрированных налоговых выплат нет. <%= link_to " Попробуйте",  new_payment_path %>
    </p>
    </h3>



    <% else %>

    <div class="row">
        <div class="col-6 " >
            <%= pie_chart Payment.group(:taxes_system).count %>
          </div>
          <div class="col-6 " >
            <%= scatter_chart Payment.pluck(:tax, :revenue), xtitle: "Tax", ytitle: "Revenue" %>
            </div>


    </div>



    <% end %>

</div>
</div>
</div>

app/views/payments/new.html.erb
<hr class="my-2">
<div class="d-flex justify-content-center">

<div class="col-8 " >
  <div class="jumbotron">
    <h2 class="display-8"> Расчет налоговых выплат</h2>
    <form>
      <hr class="my-3">

      <div class="form-group row">
        <label for="exampleFormControlSelect1" class="col-sm-2 col-form-label">Нал. с-ма:</label>
        <div class="col-sm-10">
        <select class="form-control" id="exampleFormControlSelect1">
          <option value="0">Общая налоговая система</option>
          <option value="1" >Упрощенная налоговая система (без НДС)</option>
          <option value="2">Упрощенная налоговая система (с НДС)</option>
        </select>
        </div>
      </div>



    <fieldset class="form-group" id="nds">
      <div class="row">
        <legend class="col-form-label col-sm-2 pt-0">НДС:</legend>
        <div class="col-sm-10">
          <div class="form-check">
            <input class="form-check-input" type="radio" name="gridRadios" id="gridRadios1" value="20" checked>
            <label class="form-check-label" for="gridRadios">
              20%
            </label>
          </div>
          <div class="form-check">
            <input class="form-check-input" type="radio" name="gridRadios1" id="gridRadios2" value="10">
            <label class="form-check-label" for="gridRadios1">
              10%
            </label>
          </div>
          <div class="form-check">
            <input class="form-check-input" type="radio" name="gridRadios2" id="gridRadios3" value="0">
            <label class="form-check-label" for="gridRadios2">
              0%
            </label>
          </div>

        </div>
      </div>
    </fieldset>





    <div class="form-group row" id="revenue">
      <label for="inputRevenue" class="col-sm-2 col-form-label">Выручка:</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" id="inputRevenue"  >
      </div>
    </div>

    <div class="form-group row" id="expences">
      <label for="inputExpences" class="col-sm-2 col-form-label">Затраты:</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" id="inputExpences" >
      </div>
    </div>

    <div class="form-group row" id="salary">
      <label for="inputsalary" class="col-sm-2 col-form-label">На з/п</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" id="inputsalary" placeholder="Выплаты з/п">
      </div>
    </div>




    <div class="form-group row">
      <div class="col-sm-10">
        <input class="btn btn-primary" id="calculateTax" type="button" value="Рассчитать">
      </div>
    </div>
    </form>

  </div>
</div>
</div>



<script type="text/javascript">
$(document).ready(function(){
    $("select").change(function(){
        var selSys = $(this).children("option:selected").val();
        if(selSys == 0)
        {
            $("#nds").show();
            $("#revenue").show();
            $("#expences").show();
            $("#salary").show();
        }
        else if(selSys == 1){
            $("#nds").hide();
            $("#revenue").show();
            $("#expences").hide();
            $("#salary").hide();
        }
        else if(selSys == 2){
          $("#nds").show();
             $("#revenue").show();
            $("#expences").hide();
            $("#salary").hide();
        }
    });
});
</script>

<script type="text/javascript">
$(document).ready(function(){
    $("#calculateTax").click(function(){
       var selSys = $("select").children("option:selected").val();
    var tax=0;
  var rev = parseInt($( "input[id ='inputRevenue']").val());
 var nds = parseInt($("input:checked").val());
 var ts = "";

if(selSys == 0)
        {
    var exp = parseInt($( "input[id ='inputExpences']").val());
var sal = parseInt($( "input[id ='inputsalary']").val());

    tax = rev/100*nds+(rev-exp)*18/100+34*sal/100;

      ts = "Общая СН";
        }
        else if(selSys == 1){

        tax = rev/100*5;
ts = "Упрощенная без НДС";

        }
        else if(selSys == 2){
        tax = rev/100*3 + rev/100*nds;
        ts = "Упрощенная с НДС";

        }

  $("#calculateTax").hide();


       $( "form" ).append( "<div class=\"card\">"+
 " <div class=\"card-body\"> Сумма налога: " + tax +

  "</div></div>" );

     var dataaa = {"taxes_system" : ts ,"tax" : tax, "revenue" : rev, "authenticity_token" : $('[name="csrf-token"]')[0].content}
    $.ajax({
        type:"POST",
        url:"http://localhost:3000/payments",
        data: JSON.stringify(dataaa),
        contentType: 'application/json',
        success: function(res) {
            console.log(res);
            console.log("Added");
        }.bind(this),
        error: function(xhr, status, err) {
            console.error(xhr, status, err.toString());
        }
    });


    });
});
</script>

app/views/rooms/_form.html.erb
<%= simple_form_for @room do |form| %>
  <%= form.input :name %>
  <%= form.submit "Создать", class: 'btn btn-success' %>
<% end %>

app/views/rooms/_rooms.html.erb
<div class="mb-3">
  <%= link_to new_room_path, class: 'btn btn-primary' do %>
    Создать комнату
  <% end %>
</div>

<% if @rooms.present? %>
  <nav class="nav flex-column">
    <% @rooms.each do |room| %>
      <%= link_to room.name, room_path(room), class: 'nav-link room-nav-link' %>
    <% end %>
  </nav>
<% else %>
  <div class="text-muted">
    В данный момент комнат нет
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>
  Editing room <%= @room.name %>
</h1>

<%= render partial: 'form' %>

app/views/rooms/index.html.erb
<div class="row">
  <div class="col-12 col-md-3">
    <%= render partial: 'rooms' %>
  </div>

  <div class="col">
    <div class="alert alert-primary">
      <h4 class="alert-heading">
      Приветствуем Вас в нашем чате
      </h4>

      <p>
        Вы можете присоединиться к любой комнате.
      </p>

      <hr/>

      <p>
        Также Вы можете создать комнату самостоятельно. ** По возможности тематизируйте название комнаты.
      </p>
    </div>
  </div>
</div>

app/views/rooms/new.html.erb
<h1>
  Создание команты
</h1>

<%= render partial: 'form' %>

app/views/rooms/show.html.erb
<h1>
  <%= @room.name %>
</h1>

<div class="row">
  <div class="col-12 col-md-3">
    <%= render partial: 'rooms' %>
  </div>

  <div class="col">
    <div class="chat" data-channel-subscribe="room" data-room-id="<%= @room.id %>">
      <% @room_messages.each do |room_message| %>
        <div class="chat-message-container">
          <div class="row no-gutters">
            <div class="col-auto text-center">
            <img src="<%= room_message.user.gravatar_url %>" class="avatar" alt="">
            </div>

            <div class="col">
              <div class="message-content">
                <p class="mb-1">
                  <%= room_message.message %>
                </p>

                <div class="text-right">
                  <small>
                    <%= room_message.created_at %>
                  </small>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <%= simple_form_for @room_message, remote: true do |form| %>
      <div class="input-group mb-3">
        <%= form.input :message, as: :string,
                                 wrapper: false,
                                 label: false,
                                 input_html: {
                                   class: 'chat-input'
                                 } %>
        <div class="input-group-append">
          <%= form.submit "Send", class: 'btn btn-primary chat-input' %>
        </div>
      </div>

      <%= form.input :room_id, as: :hidden %>
    <% end %>
  </div>
</div>




<div class="d-none" data-role="message-template">
  <div class="chat-message-container">
    <div class="row no-gutters">
      <div class="col-auto text-center">
        <img src="" class="avatar" alt="" data-role="user-avatar">
      </div>

      <div class="col">
        <div class="message-content">
          <p class="mb-1" data-role="message-text"></p>

          <div class="text-right">
              <p class="mb-1" data-role="message-username"></p>
            <small data-role="message-date"></small>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navigation_bar.html.erb
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>


<nav class="navbar navbar-expand-lg navbar-dark bg-dark justify-content-between">

  <%= link_to "Рассчитать налог", new_payment_path, class: "links main-link navbar-brand" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
     <span class="navbar-toggler-icon"></span>
   </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
            <%= link_to "Статистика", payments_path, class: "links nav-link" %>
        </li>
        <li class="nav-item active">
            <%= link_to "Бизнес-чат", rooms_path, class: "links nav-link" %>
        </li>
        <li class="nav-item active">
            <%= link_to "О сайте", root_path, class: "links nav-link" %>
        </li>
        <li class="nav-item active">
            <%= link_to "Контакты", home_contacts_path, class: "links nav-link" %>
        </li>

      </ul>

    </div>

  <% if current_user %>
    <div class="dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <img class="avatar" src="<%= current_user.gravatar_url %>" , class: "links">
        <%= current_user.username %>
      </a>

      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
        <%= link_to 'Выйти', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
      </div>
    </div>
  <% else %>
  <div class="btn-group" role="group" aria-label="Basic example">
      <%= link_to 'Регистрация', new_user_registration_path, class: "btn btn-primary btn-sm" %>
      <%= link_to 'Войти', new_user_session_path, class: "btn btn-outline-primary btn-sm" , style: "color: white;"%>

  </div>





  <% end %>
  </nav>